from button_data_1_lvl import RETURN_BUTTON_VALUE
from button_data_2_lvl import (
    CLOTHES_BUTTON_VALUE,
    CARE_BUTTON_VALUE,
    AMMUNITION_BUTTON_VALUE,
    FOOD_BUTTON_VALUE,
    TOYS_BUTTON_VALUE
)

USUAL_CLOTHES_BUTTON_VALUE = "👕 Звичайний одяг"
COOLING_VESTS_BUTTON_VALUE = "🦺 Охолоджувальні жилети"

CLOTHES_BUTTONS = (
    USUAL_CLOTHES_BUTTON_VALUE,
    COOLING_VESTS_BUTTON_VALUE,
    RETURN_BUTTON_VALUE
)

CLAW_CUTTER_BUTTON_VALUE = "✂️ Кігтеріз"
COMBS_BUTTON_VALUE = "💈 Чесалки"
SHAMPOO_BUTTON_VALUE = "🛁 Шампунь"

CARE_BUTTONS = (
    CLAW_CUTTER_BUTTON_VALUE,
    COMBS_BUTTON_VALUE,
    SHAMPOO_BUTTON_VALUE,
    RETURN_BUTTON_VALUE
)

DOG_HARNESS_BUTTON_VALUE = "🐕‍🦺 Шлея"
DOG_COLLAR_BUTTON_VALUE = "🎗 Нашийник"
ADDRESS_HOLDER_BUTTON_VALUE = "🏷 Адресник"
CAR_HAMMOCK_BUTTON_VALUE = "🚗 Автогамак"
DOG_LEAD_BUTTON_VALUE = "🦮 Повідок"
MUZZLE_BUTTON_VALUE = "🙊 Намордник"

AMMUNITION_BUTTONS = (
    DOG_HARNESS_BUTTON_VALUE,
    DOG_COLLAR_BUTTON_VALUE,
    ADDRESS_HOLDER_BUTTON_VALUE,
    CAR_HAMMOCK_BUTTON_VALUE,
    DOG_LEAD_BUTTON_VALUE,
    MUZZLE_BUTTON_VALUE,
    RETURN_BUTTON_VALUE
)

FOOD_PRODUCTS_BUTTON_VALUE = "🥩 Їжа"
PLATE_BUTTON_VALUE = "🍽 Миски"
DELICACY_BUTTON_VALUE = "🥓 Смаколики"

FOOD_BUTTONS = (
    FOOD_PRODUCTS_BUTTON_VALUE,
    PLATE_BUTTON_VALUE,
    DELICACY_BUTTON_VALUE,
    RETURN_BUTTON_VALUE
)

TOYS_PRODUCTS_BUTTON_VALUE = "⚾️ Іграшки"
GNAWS_BUTTON_VALUE = "🦴 Погризушки"

TOYS_BUTTONS = (
    TOYS_PRODUCTS_BUTTON_VALUE,
    GNAWS_BUTTON_VALUE,
    RETURN_BUTTON_VALUE
)

BUTTON_BY_TEXT_3_LVL = {
    CLOTHES_BUTTON_VALUE: CLOTHES_BUTTONS,
    AMMUNITION_BUTTON_VALUE: AMMUNITION_BUTTONS,
    CARE_BUTTON_VALUE: CARE_BUTTONS,
    FOOD_BUTTON_VALUE: FOOD_BUTTONS,
    TOYS_BUTTON_VALUE: TOYS_BUTTONS,
    DOG_HARNESS_BUTTON_VALUE: (RETURN_BUTTON_VALUE, )
}
